### ISSUE TITLE
displayed math results in invalid html

### ISSUE THREAD

**Issue by jordannoble** [barrysteyn/pelican_plugin-render_math#16]
Using $$..$$ to render displayed math results in \<p\>\<div\>..\</div\>\</p\>, which isn't valid HTML (div tags not allowed inside p tags). Is it possible to either put the p tags inside of the div or suppress the p tags somehow?

**Comment by itziarlopez** [comment]
this is fixed now

**Comment by barrysteyn** [comment]
This is fixed now
