### ISSUE TITLE
How to make math appear in index.html ?

### ISSUE THREAD

**Issue by notionsandnotes** [barrysteyn/pelican_plugin-render_math#19]
Math should appear inside the article summaries inside index.html. With me it is not happening. What to do? 

[This is my site](http://www.notionsandnotes.org/) and the source is available as a [github repository](https://github.com/notionsandnotes/notionsandnotes.org).

**Comment by barrysteyn** [comment]
Hi

I'm only gonna answer you tomorrow as it's quite late at night here. Just
to say that I do have a solution for you, but it will take me a week or so
to get it ready for you.

**Comment by barrysteyn** [comment]
@notionsandnotes Just wanted to say that this is not trivial to do since a summary may cut off the math. If that happens, what you generally need to do is restore the math. I have code for doing this, I am just getting it tested. I need someone to also help me test. Would you be willing to help me? All I would need from you is to download the plugin and then for you to run it and tell me if your math is rendered in the summary.

**Comment by notionsandnotes** [comment]
I will be more than happy to assist. Regarding testing, I have only one math article now. There should be more available by the next month.

I can be reached via george@notionsandnotes.org.

**Comment by barrysteyn** [comment]
Well, just leave your site up for me (specially the source on git). I can work from there. I will try get it going for you within the next week...

**Comment by notionsandnotes** [comment]
Do you want access to the web host? If you send me your ssh public key I can give it.

I will also prepare a few more(three) math articles by early next week, if you want to test.

**Comment by barrysteyn** [comment]
No, I don't need access to the web host (thanks anyways). Remember, this static html generation, so running it locally will be identical to running it on your web host :)

**Comment by barrysteyn** [comment]
Go ahead and prepare the math articles, it will help my testing. But don't change the one that you currently have up now, I am going to use it as a test case.

**Comment by barrysteyn** [comment]
@notionsandnotes Okay - clone the latest version I pushed for this plugin. Everything should work. You will need to install BeautifulSoup4 if you have not already installed it. Tell me how it comes out...

**Comment by notionsandnotes** [comment]
It works!! Check out [www.notionsandnotes.org](http://www.notiosnandnotes.org) and also [a blog post](http://www.notionsandnotes.org/tech/web-development/pelican-render_math-index-update.html) commemorating your help/contribution.

Hope the latter is ok.

Will test more next week when I have more articles. But I think that too should work fine.

Thanks man!

**Comment by barrysteyn** [comment]
Thank you so much for the kind words. Just a quick note: I updated this plugin, but as you may note, you are looking at the version that I keep on my own repo, not the version that I maintain on the official pelican plugin repo. In short: Now that it works, I will need to polish it just a bit, and then I will submit it to the official pelican plugin repo.

I keep this plugin here for *cutting edge* changes like you request. But when it eventually makes it to the pelican plugin repo, I suggest you use that version, it will be more stable.

**Comment by barrysteyn** [comment]
Hi @notionsandnotes 

Okay, I have just put a version of the plugin that I am keen to submit to the official pelican plugin page. Can you please test it for me. All you have to do is pull this repo again, run it through your site, and verify that things work.

Thanks

**Comment by notionsandnotes** [comment]
It works. I also tested with multiple articles that are not publication-ready yet(and reverted later). So no issues to report from my side.

**Comment by notionsandnotes** [comment]
Hi @barrysteyn 

 I tested it out with multiple articles(yet to upload), and it worked fine, except for:

I just enabled the pelican 'summary' plugin and used the  and  markers. These does not work if the render_math plugin is enabled.

This is the only issue I could find. If I see anything else, I will report here.

-(George S.)

**Comment by barrysteyn** [comment]
Sorry, that's a plugin, it's not part of the core pelican code. I'll only
support things that are in the core

**Comment by notionsandnotes** [comment]
Oh, OK. Thanks for what you did so far, anyway.

There are no other issues to report.

**Comment by barrysteyn** [comment]
Here is a hint though. The order of the plugins matter. See if placing that
plugin first won't make things work for you

**Comment by notionsandnotes** [comment]
No, it doesn't, but thanks. I will manage it in some way.

**Comment by notionsandnotes** [comment]
I have no idea how, but it suddenly started working, and your plugin is first.

So, all good!

**Comment by barrysteyn** [comment]
I know exactly why things are working for you (look at the code of the summaries plugin - you will see why). I decided to alter my plugin slightly so that it would play better with other plugins that do indeed alter the summary. So get the latest version of this plugin, and then try it with your summary plugin. It should work. BUT note:

 1. This plugin must come **AFTER** the summary plugin. It assumes that the summary has already been processed. Again, do not put it before
 2. Please test and get back to me ASAP.

Thanks

**Comment by notionsandnotes** [comment]
It works, and even with multiple articles. 

About, pluging coming in **AFTER** the summary plugin, my relevant section of pelicanconf.py is like this:

    PLUGINS += ['render_math']
    
    PLUGINS += ['summary']
    SUMMARY_BEGIN_MARKER = ''
    SUMMARY_END_MARKER = ''

It was written so to separate plugin-in wise settings easily. The above works, but if render_math line is put afterwards, it doesn't.

**Comment by barrysteyn** [comment]
This issue has been solved.
