### ISSUE TITLE
Pelican can't find some images after installing render_math plugin

### ISSUE THREAD

**Issue by LukasWoodtli** [barrysteyn/pelican_plugin-render_math#22]
Output of Pelican:
`WARNING: Unable to find '/images/artist_mode.svg', skipping url replacement.`

The page that is missing the imagre is available here:
http://lukaswoodtli.github.io/emacs_artist_mode.html

Strangely inclusion of an image works here:
http://lukaswoodtli.github.io/drafts/introduction_to_statistics.html

The source code to my pelican web page is here:
https://github.com/LukasWoodtli/WebPage

I use the *render_math* plugin from the official plugins repo.

This seems to be related to https://github.com/barrysteyn/pelican_plugin-render_math/issues/8

**Comment by barrysteyn** [comment]
Hi

I don't know why it is doing this, but I know it has nothing to do render_math. It is probably a plugin that is interfering, try either removing a plugin or changing the plugin order.

**Comment by barrysteyn** [comment]
I will however give you one hint: Remove `{filename}` from the image source urls, and they will work.

**Comment by LukasWoodtli** [comment]
Thank you for your help!
It didn't help to change the order of the plugins or disable all other plugins.

But if I remove the {filname} from the image link it works again...
