### ISSUE TITLE
render_math breaks generation, 404 images

### ISSUE THREAD

**Issue by sinkpoint** [barrysteyn/pelican_plugin-render_math#23]
I have the same problem, as issue 22 (https://github.com/barrysteyn/pelican_plugin-render_math/issues/22)

removing {filename} or {attach} works, but it breaks output image file generation, and files are not copied to the output. The only solution is to disable render_math, put in the {attach} tags to images, generate, then re-enable.

**Comment by barrysteyn** [comment]
This is about to be fixed really soon. It will require you get version 3.60 of pelican.

**Comment by sinkpoint** [comment]
Great, I'm currently using 3.6.0

**Comment by barrysteyn** [comment]
Hi @sinkpoint - pull the latest version of the render_math plugin from my personal repo, and tell me if the problem is fixed.

**Comment by sinkpoint** [comment]
Yes, it's fixed. Thanks!
