### ISSUE TITLE
Math on page doesn't render

### ISSUE THREAD

**Issue by tyleraland** [barrysteyn/pelican_plugin-render_math#24]
Hello, I seem to be having trouble getting your plugin working in my project.

My output contains mathjax-related javascript, but the output isn't rendered as expected.  I've tried multiple forms of initiating math mode (e.g. $$math = 4$$).  I've found a chunk of mathjax code on the web (https://www.ceremade.dauphine.fr/~amic/blog/mathjax-and-pelican.html) and if I insert that block into my theme's base.html, my math is rendered correctly.  In fact, while commenting out a large chunk I forgot a particular line -- and the inclusion of this line rendered the output correctly

Namely:
````
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
````
However I'd much rather use this plugin than use this code snippet.

In the javascript console (chrome) of the page I see:
````
Failed to load resource: net::ERR_FILE_NOT_FOUND file://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML Failed to load resource: net::ERR_FILE_NOT_FOUND
```

Here is a dump of my HTML: https://gist.github.com/tyleraland/3d9dbe8f36a58a2d4eb5

Any help would be appreciated!  Thanks

**Comment by tyleraland** [comment]
Also I should mention that the above is with my theme (blueidea) and your plugin both on master

**Comment by barrysteyn** [comment]
It is trying to find the mathjax script on your local filesystem. Are you serving through your filesystem?

**Comment by tyleraland** [comment]
For development purposes, I'm viewing this page on my local file system, although I will ultimately deploy it.  I don't have any mathjax resources installed besides what came with your repository.  I had every intention of using an externally hosted mathjax library

http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML looks valid to me, but I have no idea why it's using file://

**Comment by tyleraland** [comment]
So it seems the problem only occurs if the html file is on my local file system.  If I deploy the html file and read it from an external source (http) then the "//" is correctly mapped to http.  If I open the html file on my local file system (`man 2 open` on osx) it's opened with file:// and so this cdn link is mapped from "//" to "file://" as well.

This seems a little strange to me -- is it normal for external resources to fail to load like this when viewing a site locally?

**Comment by barrysteyn** [comment]
The reason why the source uses '//cdn...' without a protocol attached to it is because that is the way it is recommended by Mathjax to serve their assets in a protocol agnostic way. I don't think anyone thought it would be served through a filesystem. But yes, if you don't pre-pend a protocol to your asset that you want to serve, the browser will assume the protocol that is being used to serve the main site. In your case, it is file://

Nevertheless, it is dead simple to alter the plugin to cater for your use case. If you are willing to test it for me, I will alter the plugin and you can tell me if it works.

**Comment by tyleraland** [comment]
The rationale for using "//" and the larger problem of using file:// to view the html file makes sense to me now.  While I'm sure the majority of mathjax users would be fine with grabbing the library with http (rather than, say https), I recall that in the past I had issues with viewing an HTML page in https:// when an external resource embedded in the page used http://.  My browser blocked the resource outright, basically claiming that if the user thinks they're getting https:// then all of the links must be of that form as well.

I think the real problem here is a person problem -- not a code problem.  If I serve the web page from python
````
python -m SimpleHTTPServer
````
Then I can view the page fine with http://localhost:8000/simple-math.html.  I think that viewing the file from the file system as I was doing was just a wrong-headed workflow.

**Comment by barrysteyn** [comment]
Okay, I just updated the plugin. Try it here, not on the official pelican plugins, it should work for you.

**Comment by tyleraland** [comment]
Hey the http:// prefix fixes my issue everywhere -- on the local file system and it's served correctly on my hosted page as well.

Thanks!

**Comment by barrysteyn** [comment]
Excellent. A pleasure. Have fun, and if possible, I love seeing my plugin in use, so if you don't mind, can you point me to your webpage?

**Comment by tyleraland** [comment]
I plan on hosting a blog on github pages but it's still in a pretty nascent stage and subject to change: http://tyleraland.github.io/techandlife/
