### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ankush981** [barrysteyn/pelican_plugin-render_math#31]
Hi, I'm not able to get this work properly. Some guidance, please. :smile: 

What I did was clone the repo into a directory called `plugin_render_math` so that my website directory now looks like this:

```
content
fabfile.py  output          
plugin_render_math  
__pycache__  
venv
develop_server.sh  
Makefile    
pelicanconf.py  
publishconf.py      
themes
```
Then I added this to `pelicanconf.py`:

```
from plugin_render_math import render_math
PLUGINS = ['render_math']
```

Now when I finally do `pelican content`, I get this error:

`ImportError: No module named 'plugin_render_math'`

I tried to fix this by changing the line in `pelicanconf.py` to `from .plugin_render_math import render_math` but this gave the following error:

`SystemError: Parent module '' not loaded, cannot perform relative import`

I understand I'm making a silly Python mistake somewhere, but I can't figure out where. Please help a bit?

**Comment by dandavison** [comment]
Hi @ankush981 I'm totally new to pelican but this worked for me as follows:

1. create a directory "plugins" at the top level of your pelican project
2. Add the following to `pelicanconf.py`:

  ```
PLUGIN_PATHS = ['plugins']
PLUGINS = ['render_math']
  ```

3. Clone this repo (pelican_plugin-render_math) somewhere and put a symlink in your "plugins" directory. The symlink should be called "render_math" and it should point to your clone of this repo.

So here's what the structure of my pelican project looks like now:

```
.
├── Makefile
├── pelicanconf.py
├── plugins
│   └── render_math -> ../../../pelican_plugin-render_math
└── publishconf.py
```

**Comment by ankush981** [comment]
@dandavison Thanks for your answer! I was eventually able to make it work by installing the pelican plugins bundle (can't find the link now) and following their instructions. :)
