### ISSUE TITLE
compatibility with Pelican 3.7.0

### ISSUE THREAD

**Issue by szhorvat** [barrysteyn/pelican_plugin-render_math#38]
Hi Barry,

Have you tested the plugin with Pelican 3.7?  It does not seem to work.  Math is simply not processed.  I get this warning:

    WARNING: _get_summary() has been deprecated since 3.6.4. Use the summary decorator instead

which may be unrelated, and if I don't define `MD_EXTENSIONS` in my configuration, I also get 

```
Traceback (most recent call last):
  File "/Users/szhorvat/websites/pelican-site/plugins/mathjax/render_math.py", line 391, in mathjax_for_markdown
    pelicanobj.settings['MD_EXTENSIONS'].append(PelicanMathJaxExtension(config))
KeyError: 'MD_EXTENSIONS'
```

This is because `MD_EXTENSIONS` is now deprecated, as described [here](http://blog.getpelican.com/pelican-3.7-released.html).

If you need, I will add a minimal example in January.

Happy new year and thanks for maintaining this plugin! 😃

**Comment by barrysteyn** [comment]
Hi

Thanks for bringing this to my attention. I will look into this soon...
